import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseDocument } from "yaml";
import type { YAMLSeq } from "yaml";

export interface InstallGateWorkflowResult {
  destPath: string;
  written: boolean;
  conflict?: boolean;
}

const HEADER_RE = /^# generated by depaudit setup.*\n# trigger branch:.*\n/;

function stripHeader(content: string): string {
  return content.replace(HEADER_RE, "");
}

export async function installGateWorkflow(
  repoRoot: string,
  triggerBranch: string,
  options: { now?: Date } = {}
): Promise<InstallGateWorkflowResult> {
  const now = options.now ?? new Date();

  // Resolve template path: works from src/modules/ (tests) and dist/modules/ (runtime)
  const templatePath = fileURLToPath(
    new URL("../../templates/depaudit-gate.yml", import.meta.url)
  );
  const templateContent = await readFile(templatePath, "utf8");

  // Parse, set on.pull_request.branches, re-serialise
  const doc = parseDocument(templateContent);
  const on = doc.get("on") as Record<string, unknown> | null;
  if (on && typeof on === "object") {
    const prTrigger = (doc.getIn(["on", "pull_request"]) ?? {}) as Record<string, unknown>;
    doc.setIn(["on", "pull_request", "branches"], [triggerBranch]);
    void prTrigger;
  }
  const body = doc.toString();

  const header = `# generated by depaudit setup at ${now.toISOString()}\n# trigger branch: ${triggerBranch}\n`;
  const newContent = header + body;

  const destDir = join(repoRoot, ".github", "workflows");
  const destPath = join(destDir, "depaudit-gate.yml");

  // Check if destination already exists
  let existing: string | null = null;
  try {
    existing = await readFile(destPath, "utf8");
  } catch {
    existing = null;
  }

  if (existing !== null) {
    const existingBody = stripHeader(existing);
    if (existingBody === body) {
      // Byte-identical body (modulo header timestamp) — no write needed
      return { destPath, written: false };
    }
    // Different body — conflict, do not overwrite
    return { destPath, written: false, conflict: true };
  }

  await mkdir(destDir, { recursive: true });
  await writeFile(destPath, newContent, "utf8");
  return { destPath, written: true };
}
