import { describe, it, expect } from "vitest";
import { mkdtemp, rm, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parse as parseYaml } from "yaml";
import { installGateWorkflow } from "../templateInstaller.js";

async function withTempDir(fn: (dir: string) => Promise<void>): Promise<void> {
  const dir = await mkdtemp(join(tmpdir(), "depaudit-template-test-"));
  try {
    await fn(dir);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

describe("installGateWorkflow", () => {
  it("writes the workflow into a fresh directory", async () => {
    await withTempDir(async (repoRoot) => {
      const result = await installGateWorkflow(repoRoot, "main");
      expect(result.written).toBe(true);
      expect(result.destPath).toContain(".github/workflows/depaudit-gate.yml");

      const content = await readFile(result.destPath, "utf8");
      expect(content.length).toBeGreaterThan(0);
    });
  });

  it("prepends a header comment referencing the trigger branch", async () => {
    await withTempDir(async (repoRoot) => {
      const result = await installGateWorkflow(repoRoot, "develop");
      const content = await readFile(result.destPath, "utf8");
      expect(content).toMatch(/^# generated by depaudit setup at /);
      expect(content).toContain("# trigger branch: develop");
    });
  });

  it("sets on.pull_request.branches to the trigger branch", async () => {
    await withTempDir(async (repoRoot) => {
      const result = await installGateWorkflow(repoRoot, "staging");
      const content = await readFile(result.destPath, "utf8");
      // Strip header lines
      const yamlBody = content.replace(/^#.*\n#.*\n/, "");
      const parsed = parseYaml(yamlBody) as Record<string, unknown>;
      const on = parsed["on"] as Record<string, unknown>;
      const pr = on["pull_request"] as Record<string, unknown>;
      expect(pr["branches"]).toEqual(["staging"]);
    });
  });

  it("re-run with byte-identical body does not write again", async () => {
    await withTempDir(async (repoRoot) => {
      const now = new Date("2026-01-01T00:00:00.000Z");
      await installGateWorkflow(repoRoot, "main", { now });

      // Re-run with different timestamp but same branch (body is identical)
      const result2 = await installGateWorkflow(repoRoot, "main", {
        now: new Date("2026-01-02T00:00:00.000Z"),
      });
      expect(result2.written).toBe(false);
      expect(result2.conflict).toBeFalsy();
    });
  });

  it("re-run with diverged body returns conflict: true and does not overwrite", async () => {
    await withTempDir(async (repoRoot) => {
      const result1 = await installGateWorkflow(repoRoot, "main");
      expect(result1.written).toBe(true);

      // Manually write diverged content to the destination
      const destPath = result1.destPath;
      await writeFile(destPath, "# totally different\nname: other\n", "utf8");

      const result2 = await installGateWorkflow(repoRoot, "main");
      expect(result2.written).toBe(false);
      expect(result2.conflict).toBe(true);

      // Original diverged content should be preserved
      const content = await readFile(destPath, "utf8");
      expect(content).toContain("totally different");
    });
  });

  it("creates intermediate directories if missing", async () => {
    await withTempDir(async (repoRoot) => {
      // No .github/workflows/ exists yet
      const result = await installGateWorkflow(repoRoot, "main");
      expect(result.written).toBe(true);

      const { access } = await import("node:fs/promises");
      await access(result.destPath); // throws ENOENT if file not accessible
    });
  });
});
